# Generated by Django 3.2 on 2021-05-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs', models.CharField(choices=[('O', 'Oxygen'), ('P', 'Plasma')], max_length=50)),
                ('nameofp', models.CharField(max_length=50)),
                ('ageofp', models.IntegerField()),
                ('state', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=25)),
                ('address2', models.CharField(max_length=25)),
                ('pincode', models.IntegerField()),
                ('contact1', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
