# Generated by Django 3.2 on 2021-05-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply', models.CharField(choices=[('Oxygen', 'Oxygen'), ('Plasma', 'Plasma')], max_length=50)),
                ('nameofp', models.CharField(max_length=50)),
                ('ageofp', models.IntegerField()),
                ('state', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=25)),
                ('address2', models.CharField(max_length=25)),
                ('pincode', models.IntegerField()),
                ('contact1', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.AlterModelOptions(
            name='post1',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterField(
            model_name='post1',
            name='needs',
            field=models.CharField(choices=[('Oxygen', 'Oxygen'), ('Plasma', 'Plasma')], max_length=50),
        ),
    ]
